[project]
name = "continual-learning-utils"
version = "0.1.0"
description= "A Python package for continual learning algorithms and utilities."
authors = [
    { name = "Saptarshi Sarkar", email = "saptarshi.programmer@gmail.com" },
]
readme= "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
]

[project.urls]
Repository = "https://github.com/SaptarshiSarkar12/continual-learning"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cl"]
